#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2016
set -euo pipefail

STAGE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPTS_DIR=$(cd "${STAGE_DIR}/.." && pwd)
source "${SCRIPTS_DIR}/lib/common.sh"
source "${SCRIPTS_DIR}/lib/report.sh"
source "${SCRIPTS_DIR}/lib/stage-runner.sh"

STAGE_NAME='image-copy'
STAGE_STEPS=(3.1 3.2)

ocr_describe_action() {
  case "$1" in
    3.1) printf 'Step 3.1 is read-only; fix or retry failed index stage releases in build step 2.8.\n' ;;
    3.2) printf 'Copy all resolved IIB images to their versioned quay.io stage tags.\n' ;;
  esac
}

execute_3_1() {
  printf 'No automatic mutation is defined for step 3.1. Return to build step 2.8 and repair the failed or incomplete index release.\n' >&2
  return 2
}

write_copy_script() {
  local state=$1 path="${REPO_ROOT}/scripts/copy-index-images-${VERSION}-stage.sh"
  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -euo pipefail\n\n'
    printf '# Generated by one-click-release for %s. Requires VPN and quay credentials.\n' "${VERSION}"
    printf 'repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)\n'
    printf 'set -a\nsource "${repo_root}/.env"\nset +a\n'
    printf 'printf %s "${QUAY_PASSWORD}" | skopeo login quay.io -u "${QUAY_USER}" --password-stdin\n' "'%s'"
    while IFS=$'\t' read -r release _rp _status image ocp target; do
      printf '\n# %s (OCP %s)\n' "${release}" "${ocp}"
      printf 'skopeo copy --all %q %q --preserve-digests\n' "docker://${image}" "docker://${target}"
    done <"${state}"
  } >"${path}"
  chmod +x "${path}"
  printf 'Copy script written to: %s\n' "$(ocr_report_path_display "${path}")"
}

execute_3_2() {
  local state="${REPORT_BASE}/.state/image-copy-images.tsv"
  [[ -s "${state}" ]] || {
    printf 'No IIB digest state found; run image-copy verification first.\n' >&2
    return 2
  }
  if ! command -v skopeo >/dev/null 2>&1; then
    write_copy_script "${state}"
    return
  fi
  local first_image
  first_image=$(awk -F'\t' 'NR==1 {print $4}' "${state}")
  if [[ -z "${first_image}" ]] || ! skopeo inspect --no-tags "docker://${first_image}" >/dev/null 2>&1; then
    printf 'IIB registry is not reachable; generating the deferred VPN copy script.\n'
    write_copy_script "${state}"
    return
  fi
  [[ -n "${QUAY_USER:-}" && -n "${QUAY_PASSWORD:-}" ]] || {
    printf 'QUAY_USER and QUAY_PASSWORD are required.\n' >&2
    return 2
  }
  printf '%s' "${QUAY_PASSWORD}" | skopeo login quay.io -u "${QUAY_USER}" --password-stdin
  local image target
  while IFS=$'\t' read -r _release _rp _status image _ocp target; do
    skopeo copy --all "docker://${image}" "docker://${target}" --preserve-digests
  done <"${state}"
}

ocr_execute_step() { case "$1" in 3.1) execute_3_1 ;; 3.2) execute_3_2 ;; esac }
ocr_execute_stage "${1:-}" "${2:-}"
